version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "7777:80"
    depends_on:
      - web
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn --workers=4 project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine3.17
    ports:
      - "5451:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - ./.env.prod.db


volumes:
  postgres_data: